### ISSUE TITLE
Stupid question. How to compile SAMPC?

### ISSUE THREAD

**Issue by Alexander-Markelov** [dashr9230/SAMPC#1]
Stupid question. How to compile SAMPC?

**Comment by dashr9230** [comment]
If you have Visual Studio Community 2019 installed, and you have downloaded the source and extracted to a folder, then navigate to "SAMPC\client" or "SAMPC\server" you want to compile  and open the containing *.vcxproj file. After Visual Studio fully initialized, click on Build and select Build Solution. After a successful build, the binary file should be in the "SAMPC\(client or server)\Debug\" for client as "samp.dll" or for server as "server.exe". Release solution configuration on client side may will fail on compile, and the server probably succeed, but you should leave it on Debug config for now. 
If you don't have VS Community installey, you can dowloaded it for free from Microsoft's website. https://visualstudio.microsoft.com/vs/community/
When you installing VS 2019, then make sure  Windows 10 SDK (10.0.16299.0 and 10.0.18362.0) is selected in "Game development with C++". SAMPC also requires DirectX9 SDK (June 2010) in order to compile and run, which you can download from here: https://www.microsoft.com/en-us/download/details.aspx?id=6812

Note that SAMPC is still in development and its not in that state where you can use it online, only for test porpuses, this is the reason why binaries are not available yet for this repo.

Also if you have Discord, and you'd like to join the SAMPC community, you can join this little server.
https://discord.gg/3ppxdRm

**Comment by Alexander-Markelov** [comment]
Thanks for the answer. I'm sorry that I communicate via Yandex Translate, I'm from Russia. I hope Kalcor doesn't close this project because of the 0.2 source code, as it did with the guys from RW:MP, who eventually had to try to create their own multiplayer from scratch.
